if (self.CavalryLogger) { CavalryLogger.start_js(["bq8\/5IN"]); }

__d("jsExtraRouteBuilder",["jsRouteBuilder","unrecoverableViolation"],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a,c,d,e){var f=b("jsRouteBuilder")(a,c,e),g=d.reduce(function(a,d){a===void 0&&(a={});typeof d==="string"&&(a[d]=b("jsRouteBuilder")(d,c,e,null,!0).buildURL);return a},{});return{buildExtraURL:function(a,c){if(typeof a!=="string"||g[a]==null)throw b("unrecoverableViolation")("Route builder for extra path does not exist","comet_infra");return g[a](c)},buildURL:function(a){return f.buildURL(a)}}}}),null);
__d("XUpdateTimezoneControllerRouteBuilder",["jsExtraRouteBuilder"],(function(a,b,c,d,e,f){a=b("jsExtraRouteBuilder")("/ajax/autoset_timezone_ajax/",Object.freeze({is_forced:!1}),["/ajax/autoset_timezone_ajax.php","/ajax/timezone/update/","/ajax/timezone/update.php"],void 0);c=a;e.exports=c}),null);
__d("getBrowserGMTOffsetAdjustedForSkew",["DateConsts","FBLogger"],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a){var c,d=(c=b("DateConsts")).MIN_PER_HOUR*c.HOUR_PER_DAY,e=new Date(),f=e.getTimezoneOffset();e=e.getTime()/c.MS_PER_SEC;var g=15;a=a-e;e=Math.round(a/(g*c.SEC_PER_MIN))*g;e!=0&&b("FBLogger")("TimezoneAutoset").info("Adjusting timezone offset for clock skew. Browser offset: %s. Raw skew %s. Rounded skew %s",f,a,e);c=Math.round(f+e)%d;c>12*b("DateConsts").MIN_PER_HOUR?c-=d:c<-14*b("DateConsts").MIN_PER_HOUR&&(c+=d);return c}}),null);
__d("getBrowserTimezone",["FBLogger"],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(){try{var a;a=((a=window.Intl)==null?void 0:a.DateTimeFormat)&&Intl.DateTimeFormat();a=(a==null?void 0:a.resolvedOptions)&&a.resolvedOptions();return a==null?void 0:a.timeZone}catch(a){b("FBLogger")("TimezoneAutoset").catching(a).warn("Could not read IANA timezone from browser");return null}}}),null);
__d("TimezoneAutoset",["AsyncRequest","XUpdateTimezoneControllerRouteBuilder","emptyFunction","getBrowserGMTOffsetAdjustedForSkew","getBrowserTimezone","killswitch"],(function(a,b,c,d,e,f){var g=!1;function a(a,b,c){h({serverTimestamp:a,serverTimezone:null,serverGmtOffset:b,forceUpdate:c})}function h(a){var c=a.serverTimestamp,d=a.serverTimezone,e=a.serverGmtOffset;a=a.forceUpdate;if(!c||e==null)return;if(g)return;g=!0;c=-b("getBrowserGMTOffsetAdjustedForSkew")(c);var f=b("killswitch")("TIMEZONE_SET_IANA_ZONE_NAME")?null:b("getBrowserTimezone")();if(a||c!=e||f!=null&&f!=d){e=b("XUpdateTimezoneControllerRouteBuilder").buildExtraURL("/ajax/timezone/update.php",{});new(b("AsyncRequest"))().setURI(e).setData({tz:f,gmt_off:c,is_forced:a}).setErrorHandler(b("emptyFunction")).setTransportErrorHandler(b("emptyFunction")).setOption("suppressErrorAlerts",!0).send()}}c={setInputValue:function(a,c){a.value=b("getBrowserGMTOffsetAdjustedForSkew")(c).toString()},setTimezone:a,getBrowserTimezone:b("getBrowserTimezone"),setTimezoneAndOffset:h};e.exports=c}),null);
__d("FlipDirection",["DOM","Input","Style"],(function(a,b,c,d,e,f){a={setDirection:function(a,c,d){c===void 0&&(c=5);d===void 0&&(d=!1);var e=b("DOM").isNodeOfType(a,"input")&&a.type=="text",f=b("DOM").isNodeOfType(a,"textarea");if(!(e||f)||a.getAttribute("data-prevent-auto-flip"))return;e=b("Input").getValue(a);f=a.style&&a.style.direction;if(!f||d){f=0;d=!0;for(var g=0;g<e.length;g++){var h=e.charCodeAt(g);if(h>=48){d&&(d=!1,f++);if(h>=1470&&h<=1920){b("Style").set(a,"direction","rtl");a.setAttribute("dir","rtl");return}if(f==c){b("Style").set(a,"direction","ltr");a.setAttribute("dir","ltr");return}}else d=!0}}else e.length===0&&(b("Style").set(a,"direction",""),a.removeAttribute("dir"))}};e.exports=a}),null);
__d("FlipDirectionOnKeypress",["Event","FlipDirection"],(function(a,b,c,d,e,f){a=function(a){a=a.getTarget();b("FlipDirection").setDirection(a)};b("Event").listen(document.documentElement,{keyup:a,input:a})}),null);
__d("ScreenDimensionsAutoSet",[],(function(a,b,c,d,e,f){f.getScreenDimensions=g;f.setInputValue=a;function g(){if(!window.btoa)return"";var a={w:screen.width,h:screen.height,aw:screen.availWidth,ah:screen.availHeight,c:screen.colorDepth};return btoa(JSON.stringify(a))}function a(a){a.value=g()}}),null);
__d("MessengerMarketingBannerPosition",["cx","CSS","Event","throttle"],(function(a,b,c,d,e,f,g){"use strict";a={init:function(a){var c=a.root;b("Event").listen(window,"scroll",b("throttle")(function(){d(c)},100));function d(a){var c=window.document.body.getBoundingClientRect();c=window.innerHeight-parseInt(c.height+c.top,10);b("CSS").conditionClass(a,"_9gb4",c===0||c===1)}}};e.exports=a}),null);
__d("MessengerMarketingClose",["CSS","Event"],(function(a,b,c,d,e,f){"use strict";a={init:function(a){b("Event").listen(a.closeButton,"click",function(){b("CSS").hide(a.root)})}};e.exports=a}),null);
__d("MessengerMarketingHeader",["cx","CSS","Style"],(function(a,b,c,d,e,f,g){a=function(){a.create=function(b,c,d){return new a(b,c,d)};function a(a,b,c){var d=this;this.onScroll=function(){window.scrollY<d.top?(d.fixed&&d.toggleFixed(),d.toggleBgOpacity(!1,0)):(d.fixed||d.toggleFixed(),window.scrollY-d.top<d.fade?d.toggleBgOpacity(!1,(window.scrollY-d.top)/d.fade):d.bgShowing||d.toggleBgOpacity(!0,1))};this.root=a;this.bg=b;this.fade=60;this.top=c;this.fixed=!1;this.bgShowing=!1;h(window,"scroll",this.onScroll)}var c=a.prototype;c.toggleFixed=function(){this.fixed=!this.fixed,this.fixed?b("CSS").addClass(this.root,"_6a88"):b("CSS").removeClass(this.root,"_6a88")};c.toggleBgOpacity=function(a,c){this.bgShowing=a,b("Style").set(this.bg,"opacity",c)};return a}();e.exports=a;function h(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}}),null);
__d("MessengerMarketingLanguageToggle",["cx","CSS","Event","containsNode"],(function(a,b,c,d,e,f,g){a={init:function(a){var c=a.button,d=a.container;b("Event").listen(c,"click",function(){b("CSS").addClass(d,"_8vbi")});b("Event").listen(window,"click",function(a){b("containsNode")(d,a.target)||b("CSS").removeClass(d,"_8vbi")})}};e.exports=a}),null);
__d("MessengerMarketingMobileMenu",["csx","cx","Event","debounce"],(function(a,b,c,d,e,f,g,h){var i="._8otc",j="_8otd";e.exports={addHandlers:function(a){var c=a.querySelector(i);if(!c)return;a=k(a);b("Event").listen(c,"click",a);b("Event").listen(c,"touchstart",a)}};function k(a){return b("debounce")(function(){return a.classList.toggle(j)},300,!0)}}),null);