P.register("cvfVersion",function(){return{version:"0.1.0.0-2021-02-19"}});"use strict";
P.when("A","cvfFormDataGenerator","ready").register("cvf-account-switcher",function(b,d){function a(r,a){r.preventDefault();var c=d.retrieveFormData(r.target),g=c.inputData.serializeArray();g.push(m(r.target));b.ajax(window.location.protocol+"//"+window.location.host+c.requestPath,{method:"POST",params:g,success:a,error:k})}function m(a){a=c(a);var b=a.attr("name");b||(b=a.closest(".cvf-account-switcher-sign-out-link").attr("data-name"));var e=a.attr("value");e||(e=a.closest(".cvf-account-switcher-sign-out-link").attr("data-value"));
return{name:b,value:e}}function k(a,c,e){b.trigger(q.error,e)}function h(a){var b=/([^@\s]+)@([a-zA-Z0-9_-]+)(\.[a-zA-Z0-9._-]+)/ig.exec(a);if(null!==b){a=b[1];a=c.trim(a);var e=a.length;if(1!==e){for(var g=a.charAt(0),d=0;d<e-2;d++)g+="*";a=g+=a.charAt(e-1)}a+="@";g=b[2];g=c.trim(g);e=g.length;g=g.charAt(0);for(d=0;d<e-1;d++)g+="*";return a+g+b[3]}b=c.trim(a);a=b.length;if(!(4>=a)){e="";for(g=0;g<a-4;g++)e+="*";b=e+b.substr(a-4,a-1)}return b}function n(){0===c(".cvf-account-switcher-check-mark:visible").length&&
(c(".cvf-account-switcher-check-mark-area").remove(),c(".cvf-account-switcher-profile-details").toggleClass("cvf-account-switcher-profile-details cvf-account-switcher-profile-details-after-account-removed"))}var c=b.$,q={success:"cvf:account_switcher:success",error:"cvf:account_switcher:error"};(function(){var a=c("#ap-account-switcher-container")[0],b=window.MutationObserver||window.WebKitMutationObserver;if(void 0!==a&&void 0!==b){var d=new b(function(a){for(var b=0;b<a.length;b++)if(null!==a[b].addedNodes){n();
d.disconnect();break}});d.observe(a,{attributes:!0,childList:!0,characterData:!0,subtree:!0})}})();(function(){c(".cvf-account-switcher-sign-out-link").live("click",function(d){a(d,function(a){if(a.redirectUrl)window.location=a.redirectUrl,b.trigger("cvf:account_switcher","redirectOnSignOut");else if(a.succeeded){var e="."+c(d.target).attr("class").match(/cvf-account-switcher-account-group-\w+/g)[0];c(e+"-hide").hide();c(e+"-name").text(c("#cvf-account-switcher-sign-out-replace-text").text());c(e+
"-claim").text(h(c(e+"-claim").text()));c(e+"-image").replaceWith(c("\x3cdiv /\x3e").append(c("#cvf-account-switcher-sign-out-replace-image").clone().removeClass("cvf-hidden")).html());c(e+"-button").removeClass("cvf-widget-btn-val cvf-widget-btn-verify-account-switcher");a=a.switchedAccountId;void 0!==a&&c(".cvf-account-switcher-account-group-"+a+"-check-mark").show();n()}else b.trigger(q.error,a)})})})()});"use strict";P.when("A","cvfFormDataGenerator","ready").execute(function(b,d){});"use strict";
P.when("A","ready").register("codeAutoVerify",function(b){b=b.$;var d=b("#cvf-auto-verify-form");0<d.length&&(window.submitVerificationCode=function(a){d.find("#cvf-enter-code").val(a);d.submit()})});P.when("A","ready").register("codeAutoReadTimer",function(b){var d=b.$,a=d("#cvf-auto-verification-failed");a.length&&b.delay(function(){a[0].click()},3E4)});"use strict";
P.when("A","ready").register("codeResendTimer",function(b){function d(a,d,k){var h=(new Date).getTime(),n=setInterval(function(){var c=(new Date).getTime()-h,c=a-c;if(0>=c)clearInterval(n),b.$("#timer").html(k);else{var c=Math.floor(c/1E3),q=d.split(" +timeleft+ "),c=q[0].split('"').join("")+c+q[1].split('"').join("");b.$("#timer").html(c)}},100)}return{createTimer:function(a,b,k){return new d(a,b,k)}}});"use strict";
P.when("A","cvfFormDataGenerator","ready").execute(function(b,d){var a=b.$;a(".cvf-widget-btn-val").click(function(b){var k=a(b.target).closest(".cvf-widget-form");b=d.getNameValue(a(b.target));k.append('\x3cinput type\x3d"hidden" name\x3d"'+b.name+'" value\x3d"'+b.value+'"\x3e').submit()})});"use strict";
P.when("A","cvfVersion","cvfFormDataGenerator","ready").register("cvf",function(b,d,a){function m(q){function k(a){"string"===typeof f.options.widgetMetricsScope&&"function"===typeof window.uet&&window.uex("ld",f.options.widgetMetricsScope,{wb:1});f.options.spinnerTarget&&f.options.spinnerTarget.hide();a.hasOwnProperty("error")?b.trigger(l.error,a.error):a.redirectUrl?window.location=a.redirectUrl:a.redirect?(b.trigger(l.success,a.token,a.status,a.redirect),f.options.autoDestroy?f.destroy():(h(".cvf-widget-alert").hide(),
a.status?h(".cvf-widget-status-success").show():h(".cvf-widget-status-error").show(),w()),b.trigger("cvf:verification:complete",a.status),p.find(".cvf-widget-btn").unbind("click",m),p.find(".cvf-widget-btn-val").unbind("click",m),b.off(l.success),b.off(l.error)):(p.html(a.replace(/<form/g,"\x3cdiv").replace(/<\/form/g,"\x3c/div")),g())}function m(d,c){d.preventDefault();h(".cvf-widget-alert").hide();f.options.spinnerTarget&&f.options.spinnerTarget.show();var e=a.retrieveFormData(d.target),g=e.inputData.serializeArray();
c&&g.push(a.getNameValue(d.target));b.ajax(t+e.requestPath,{method:"POST",params:g,success:k,error:x})}function e(a){13===a.keyCode&&m(a)}function g(){p.find(".cvf-widget-btn").click(function(a){m(a,!1)});p.find(".cvf-widget-btn-val").click(function(a){m(a,!0)});p.find('input[name\x3d"code"]').focus().keypress(e)}function v(a){return function(d,c,e){"timeout"!==c||3<=u?b.trigger(l.error,e):b.delay(a,10*u++)}}function x(a,d,c){f.options.spinnerTarget&&f.options.spinnerTarget.hide();b.trigger(l.error,
c)}function w(){h.each(p.find("input"),function(a,b){a=h(b);a.attr("disabled","disabled");a.hasClass("a-input-text")?a.addClass("a-form-disabled"):a.hasClass("a-button-input")?a.closest(".a-button").addClass("a-button-disabled"):a.closest(".a-input-text-wrapper").length&&a.closest(".a-input-text-wrapper").addClass("a-form-disabled")});h.each(p.find("a"),function(a,b){a=h(b);a.hasClass("cvf-widget-link-disable-target")&&a.addClass("cvf-link-disabled")})}var f=this;c++;var l={success:"cvf:"+c+":success",
error:"cvf:"+c+":error"};f.options={};h.extend(f.options,n,q);(function(a){if(1!==h(a.target).length)throw Error("The CVF widget requires a unique element.");if(!h.isFunction(a.onSuccess))throw Error("The CVF widget requires a success callback function.");if(!h.isFunction(a.onError))throw Error("The CVF widget requires an error callback function.");})(f.options);var t=f.options.server,p=h(f.options.target);b.on(l.success,f.options.onSuccess);b.on(l.error,f.options.onError);f.start=function(){if(0===
h.trim(f.options.requestToken).length)throw Error("The CVF widget requires a request token.");var a=t+"/ap/cvf/request.embed",c=f.options.requestToken,e=f.options.requestArbToken,g=f.options.associationHandle,q=f.options.language,m=0===h.trim(e).length,n=0!==h.trim(g).length,p=0!==h.trim(q).length,l={};m?l.requestToken=c:l.arb=e;l.CVFVersion=d.version;l.AUIVersion=P.AUI_BUILD_DATE;p&&(l.language=q);n&&(l["openid.assoc_handle"]=g);"string"===typeof f.options.widgetMetricsScope&&"function"===typeof window.uet&&
window.uet("bb",f.options.widgetMetricsScope,{wb:1});b.ajax(a,{method:"GET",params:l,success:k,error:v(f.start)})};f.destroy=function(){p.html("")};g();var u=0;f.options.autoStart&&f.start()}function k(a){return new m(a)}var h=b.$,n={server:"",target:void 0,requestToken:void 0,requestArbToken:void 0,onSuccess:void 0,onError:void 0,spinnerTarget:void 0,autoStart:!0,autoDestroy:!0,widgetMetricsScope:void 0,associationHandle:void 0,language:void 0},c=0;b.on("cvf:verification:request",function(a){var c=
h("#"+a),d=c.data("token"),e=c.data("spinnerId"),e=h("#"+e);k({target:c,spinnerTarget:e,requestToken:d,onSuccess:function(c,d,e){b.trigger("cvf:verification:complete:"+a,c,d,e)},onError:function(c){b.trigger("cvf:verification:error:"+a,c)},autoStart:!0,autoDestroy:!1})});return{create:k}});"use strict";
P.when("A","ready").register("cvfFormDataGenerator",function(b){var d=b.$;return{retrieveFormData:function(a){a=d(a).closest(".cvf-widget-form");return{requestPath:a.data("use-only-form-action")?a.attr("action"):"/ap/cvf/"+a.attr("action")+".embed",inputData:a.find(".cvf-widget-input,.cvf-widget-hidden-fields,.cvf-widget-input :input"),form:a}},getNameValue:function(a){a=d(a);var b=a.attr("name");b||(b=a.closest(".cvf-widget-btn-val").attr("data-name"));var k=a.attr("value");k||(k=a.closest(".cvf-widget-btn-val").attr("data-value"));
return{name:b,value:k}}}});"use strict";P.when("A","cvf","ready").execute(function(b,d){var a=b.$;a(document).ready(function(){function b(a,c,d){window.location=d;console.log("Client Side: "+a)}function k(a){console.log(a)}var h=a(".cvf-widget-spinner"),n=a("#cvf-widget-content");if(1===n.length){var c=a('[name\x3d"requestToken"]').first().attr("value");d.create({target:n,spinnerTarget:h,requestToken:c,onSuccess:b,onError:k,autoStart:!1})}})});"use strict";
P.when("A").execute(function(b){b.declarative("auth-popup","click",function(b){var a=b.data;b=b.$target.closest("a")[0];(a=window.open(b.href,b.target,a.windowOptions))&&a.focus()})});